version: '3.8'

services:
  # Redis (standard)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=password123
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Dragonfly (Redis-compatible, high performance)
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ports:
      - "6380:6379"
    command: --logtostderr --alsologtostderr
    volumes:
      - dragonfly_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Valkey (Redis-compatible, high performance)
  valkey:
    image: valkey/valkey:7-alpine
    ports:
      - "6381:6379"
    command: valkey-server --appendonly yes
    volumes:
      - valkey_data:/data
    environment:
      - VALKEY_PASSWORD=password123
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # ClickHouse (for analytics and time-series data)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    environment:
      - CLICKHOUSE_DB=ratelimit
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  dragonfly_data:
  valkey_data:
  clickhouse_data: 